app/auth_templates/urls.py
from django.urls import path
from auth_templates.views import LoginView, RegisterView, LogoutView


app_name = 'auth_templates'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

app/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/sites/')),
    path('admin/', admin.site.urls),
    path('auth/', include('auth_templates.urls')),
    path('profile/', include('user_profile.urls')),
    path('sites/', include('sites.urls')),
    path('proxy/', include('proxy.urls')),
]

app/auth_templates/forms.py
from django.contrib.auth import get_user_model
from django import forms
from users.models import CustomUser


User: CustomUser = get_user_model()


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def get_user(self):
        return User.objects.get(email=self.cleaned_data.get("email"))

    def is_valid(self) -> bool:
        valid = super(LoginForm, self).is_valid()

        if not valid:
            return valid

        try:
            user = User.objects.get(email=self.cleaned_data.get("email"))
        except User.DoesNotExist:
            self.add_error("email", "User does not exist")
            return False

        if not user.check_password(self.cleaned_data.get("password")):
            self.add_error("password", "Incorrect password")
            return False

        return True


class RegisterForm(forms.Form):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def is_valid(self) -> bool:
        valid = super(RegisterForm, self).is_valid()

        if not valid:
            return valid

        if User.objects.filter(email=self.cleaned_data.get("email")).exists():
            self.add_error("email", "User already exists")
            return False

        if self.cleaned_data.get("password1") != self.cleaned_data.get("password2"):
            self.add_error("password2", "Passwords do not match")
            return False

        return True

    def save(self, commit=True):
        print(self.cleaned_data)
        user = User.objects.create_user(
            email=self.cleaned_data.get("email"),
            password=self.cleaned_data.get("password1"),
        )
        return user

app/auth_templates/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login, logout
from django.views.generic import View
from .forms import LoginForm, RegisterForm


class LoginView(View):
    form_class = LoginForm
    template_name = 'auth_templates/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('sites:site-list'))
        else:
            return render(request, self.template_name, {'form': self.form_class})

    def post(self, request, *args, **kwargs):
        form = LoginForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect(reverse('sites:site-list'))
        else:
            return render(request, self.template_name, {'form': form})


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'auth_templates/register.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('sites:site-list'))
        else:
            return render(request, self.template_name, {'form': self.form_class})

    def post(self, request, *args, **kwargs):
        form = RegisterForm(data=request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('sites:site-list'))
        else:
            return render(request, self.template_name, {'form': form})


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse('auth_templates:login'))

app/auth_templates/templates/auth_templates/login.html
{% extends "common/base.html" %}

{% block content %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'auth_templates:login' %}">
{% csrf_token %}
<div class="form-group">
    <p class="text-danger">{{ form.email.errors }}</p>
    <label for="id_email">Email address</label>
    <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter email">
</div>
<div class="form-group">
    <p class="text-danger">{{ form.password.errors }}</p>
    <label for="id_password">Password</label>
    <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
</div>
<input type="submit" value="login" class="btn btn-primary mt-2">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

app/auth_templates/templates/auth_templates/register.html
{% extends "common/base.html" %}

{% block content %}

<form method="post" action="{% url 'auth_templates:register' %}">
{% csrf_token %}
<div class="form-group">
    <p class="text-danger">{{ form.email.errors }}</p>
    <label for="id_email">Email address</label>
    <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter email">
</div>
<div class="form-group">
    <p class="text-danger">{{ form.password1.errors }}</p>
    <label for="id_password">Password</label>
    <input type="password1" class="form-control" id="id_password" name="password1" placeholder="Password">
</div>
<div class="form-group">
    <p class="text-danger">{{ form.password2.errors }}</p>
    <label for="id_password">Confirm password</label>
    <input type="password2" class="form-control" id="id_password" name="password2" placeholder="Password">
</div>
<input type="submit" value="register" class="btn btn-primary mt-2">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}