app/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/sites/')),
    path('admin/', admin.site.urls),
    path('auth/', include('auth_templates.urls')),
    path('profile/', include('user_profile.urls')),
    path('sites/', include('sites.urls')),
    path('proxy/', include('proxy.urls')),
]

app/proxy/urls.py
from django.urls import path
from .views import ProxyIndexView

app_name = 'proxy'
urlpatterns = [
    path('', ProxyIndexView.as_view(), name='index'),
]

app/sites/urls.py
from django.urls import path
from .views import SiteListView, SiteDetailView, SiteCreateView, SiteUpdateView, SiteDeleteView


app_name = 'sites'
urlpatterns = [
    path('', SiteListView.as_view(), name='site-list'),
    path('<int:pk>/', SiteDetailView.as_view(), name='site-detail'),
    path('create/', SiteCreateView.as_view(), name='site-create'),
    path('<int:pk>/update/', SiteUpdateView.as_view(), name='site-update'),
    path('<int:pk>/delete/', SiteDeleteView.as_view(), name='site-delete'),
]

app/sites/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Site(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users')
    visiting_count = models.BigIntegerField(default=0)
    data_volume = models.BigIntegerField(default=0)

app/sites/forms.py
from django.contrib.auth import get_user_model
from django.forms import ModelForm
from users.models import CustomUser
from .models import Site


User: CustomUser = get_user_model()


class SiteForm(ModelForm):
    class Meta:
        model = Site
        fields = ['name', 'url']

app/sites/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .models import Site
from .forms import SiteForm


class SiteListView(LoginRequiredMixin, View):
    model = Site
    template_name = 'sites/site_list.html'
    context_object_name = 'sites'

    def get_queryset(self):
        return self.model.objects.all().filter(user=self.request.user)

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        context = {
            self.context_object_name: self.get_queryset(),
            'form': SiteForm()
        }
        return render(request, self.template_name, context)


class SiteDetailView(LoginRequiredMixin, View):
    template_name = 'sites/site_update.html'
    context_object_name = 'form'

    def get(self, request: HttpRequest, pk, *args: str, **kwargs: Any) -> HttpResponse:
        site = get_object_or_404(Site, pk=pk)

        if site.user != request.user:
            return redirect(reverse('sites:site-list'))

        form = SiteForm(instance=site)
        return render(request, self.template_name, {'form': form, 'site': site})


class SiteCreateView(LoginRequiredMixin, View):
    success_url = reverse_lazy('sites:site-list')

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = SiteForm(request.POST)
        if form.is_valid():
            site: Site = form.save(commit=False)
            site.user = request.user
            site.save()
            return redirect(self.success_url)
        else:
            message = form.errors
            messages.error(request, 'There is form errors', extra_tags='alert alert-danger')
            messages.error(request, message, extra_tags='alert alert-danger')
            return redirect(self.success_url)


class SiteUpdateView(LoginRequiredMixin, View):
    success_url = reverse_lazy('sites:site-list')

    def post(self, request: HttpRequest, pk, *args: str, **kwargs: Any) -> HttpResponse:
        site = get_object_or_404(Site, pk=pk)

        if site.user != request.user:
            return redirect(reverse('sites:site-list'))

        form = SiteForm(request.POST, instance=site)
        if form.is_valid():
            site: Site = form.save(commit=False)
            site.user = request.user
            site.save()
            return redirect(self.success_url)
        else:
            message = form.errors
            messages.error(request, 'There is form errors', extra_tags='alert alert-danger')
            messages.error(request, message, extra_tags='alert alert-danger')
            return redirect(self.success_url)


class SiteDeleteView(LoginRequiredMixin, DeleteView):
    model = Site
    template_name = 'sites/site_confirm_delete.html'
    success_url = reverse_lazy('sites:site-list')

    def post(self, request, *args: str, **kwargs):
        site: Site = self.get_object()

        if site.user != request.user:
            return redirect(reverse('sites:site-list'))

        response = super().post(request, *args, **kwargs)

        if response.status_code < 400:
            message = f'Site {site.name} was deleted'
            messages.success(request, message, extra_tags='alert alert-success')

        return response

app/sites/templates/sites/site_list.html
{% extends "common/base.html" %}

{% load custom_filters %}

{% block head %}
<style>
    .d-flex {
        gap: 10px;
    }
</style>
{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages mb-2 mt-2 p-0">
    {% for message in messages %}
    <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</ul>
{% endif %}

<h1>Create new site</h1>
<form action="{% url 'sites:site-create' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Site name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Enter site name">
    </div>
    <div class="form-group mb-2">
      <label for="url">Site URL</label>
      <input type="text" class="form-control" id="url" name="url" placeholder="Enter site URL">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

<h1>Sites</h1>
{% for site in sites %}
    <div class="card row pb-2 mb-2 mt-2">
        <div class="col-md-12">
            <h2>{{ site.name|truncatechars:100 }}</h2>
            <p><bold class="fw-bold">Url</bold>: {{ site.url }}</p>
            <p><bold class="fw-bold">Visiting Count</bold>: {{ site.visiting_count }}</p>
            <p><bold class="fw-bold">Data Volume</bold>: {{ site.data_volume|divide:1000000 }} mb</p>

            <div class="d-flex flex-row">
                <a class="btn btn-success" href="{% url 'proxy:index' %}?url={{site.url}}&pk={{site.pk}}" target="_blank">Visit</a>
                <a class="btn btn-primary" href="{% url 'sites:site-detail' site.id %}">Update</a>
                <form class="ml-2" action="{% url 'sites:site-delete' site.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}

app/sites/templates/sites/site_update.html
{% extends "common/base.html" %}

{% block content %}

<h1>Detail & Update site</h1>
<form action="{% url 'sites:site-update' site.pk %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Site name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Enter site name" value="{{form.name.value}}">
    </div>
    <div class="form-group mb-2">
      <label for="url">Site URL</label>
      <input type="text" class="form-control" id="url" name="url" placeholder="Enter site URL" value="{{form.url.value}}">
    </div>
    <p>Visiting Count: {{ site.visiting_count }}</p>
    <p>Data Volume: {{ site.data_volume }}</p>
    <button type="submit" class="btn btn-primary">Update</button>
</form>

{% endblock %}