app/auth_templates/urls.py
from django.urls import path
from auth_templates.views import LoginView, RegisterView, LogoutView


app_name = 'auth_templates'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

app/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/sites/')),
    path('admin/', admin.site.urls),
    path('auth/', include('auth_templates.urls')),
    path('profile/', include('user_profile.urls')),
    path('sites/', include('sites.urls')),
    path('proxy/', include('proxy.urls')),
]

app/sites/urls.py
from django.urls import path
from .views import SiteListView, SiteDetailView, SiteCreateView, SiteUpdateView, SiteDeleteView


app_name = 'sites'
urlpatterns = [
    path('', SiteListView.as_view(), name='site-list'),
    path('<int:pk>/', SiteDetailView.as_view(), name='site-detail'),
    path('create/', SiteCreateView.as_view(), name='site-create'),
    path('<int:pk>/update/', SiteUpdateView.as_view(), name='site-update'),
    path('<int:pk>/delete/', SiteDeleteView.as_view(), name='site-delete'),
]

app/user_profile/urls.py
from django.urls import path
# from .views import OrderList, OrderDelete
from .views import Index

app_name = 'user_profile'
urlpatterns = [
    path('', Index.as_view(), name='index'),
]

app/common/models.py
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth import get_user_model


class EmailBackend(ModelBackend):
    def authenticate(self, request, email=None, password=None, **kwargs):
        UserModel = get_user_model()
        try:
            user = UserModel.objects.get(email=email)
        except UserModel.DoesNotExist:
            return None
        else:
            if user.check_password(password):
                return user
        return None

app/common/templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block head %} {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'user_profile:index' %}">Profile</a>
            <a class="navbar-brand" href="{% url 'sites:site-list' %}">Sites</a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="navbar-brand" href="{% url 'auth_templates:logout' %}">Logout</a>
                        {% else %}
                            <a class="navbar-brand" href="{% url 'auth_templates:login' %}">Login</a>
                            <a class="navbar-brand" href="{% url 'auth_templates:register' %}">Register</a>
                        {% endif %}
                    </li>
                </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
</body>
</html>